# https://taskfile.dev

version: '2'

env:
  GO111MODULE: on

tasks:
  test:
    cmds:
      - go test --race ./...
  build:
    cmds:
      - go build ./cmd/tenerife-ws
  clean:
    cmds:
      - rm tenerife-ws
